name: Custom Summary

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build"
          echo "test, and deploy your project."

      - name: Write Custom Summary
        run: |
          {
            echo '### Hello world! :rocket:'
            echo '### Love this feature! :medal_sports:'
            echo ''
            echo '**Great feature!**'
          } >> "$GITHUB_STEP_SUMMARY"
