name: My First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  MyFirstJob:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os_version: [ubuntu-latest]
        node_version: [12, 14, 16]
    runs-on: ${{ matrix.os_version }}
    steps:
      - run: echo "Hello World"
      
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: List files in the repository
        shell: bash
        run: |
          echo "The repository ${{github.repository}} contains the following files:"
          tree

      - name: Testing warning
        run: echo "::warning file=app.js,line=1,col=5,endColumn=8::Env key inside app.js"

      - name: Testing error
        run: echo "::error file=app.js,line=1,col=5,endColumn=8::Error using npm in app.js"

        
      

    
