name: CI using other actions

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env: 
  PG_VAR: ${{vars.PG_VAR}}
  PG_SECRET: ${{secrets.PG}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run other action
        uses: ./.github/actions/
        with: 
          pg_var: PG_VAR
          pg_secret: PG_SECRET
